### ISSUE TITLE
Is it possible to get a project like a one point API

### ISSUE THREAD

**Issue by sinys5** [SqlToys/SqlFormat#1]
Hello,
As far I understand you have two projects SqlFormat and SqlFormatter. One git project have Delphi Form Project and next one have Delphi Command line Project. I want to use your code in my project and I need simple code call interface without Forms and Command lines projects. I need something like
(string) formattedSQL := (function) YourFormetterFunction( (string) unformattedSQLText, (complex type) FormatterOptionsSet);
Is it possible to get a project with pure SQL formatter like a library? I mean no dll, I mean I want one formatter function without forms and command line projects.

**Comment by SqlToys** [comment]
Hey,
Sorry for the delay, I didn't expect issues in this project :smile:
Look at test unit, function QueryParseFormat, it works the way you want.
Tom.
